import Foundation
import SwiftData

/// The built-in movement library — 270 exercises covering barbell, dumbbell,
/// machine, cable, kettlebell, band, sled and bodyweight work, each tagged with
/// how it should be measured. Anything missing is still one tap away via the
/// picker's "Create" row.
enum Seed {
    struct Row {
        let name: String
        let muscle: MuscleGroup
        let equipment: Equipment
        var tracking: TrackingStyle = .weightAndReps
    }

    static let exercises: [Row] = [
        // MARK: chest
        .init(name: "Bench Press", muscle: .chest, equipment: .barbell),
        .init(name: "Incline Bench Press", muscle: .chest, equipment: .barbell),
        .init(name: "Decline Bench Press", muscle: .chest, equipment: .barbell),
        .init(name: "Close-Grip Bench Press", muscle: .chest, equipment: .barbell),
        .init(name: "Floor Press", muscle: .chest, equipment: .barbell),
        .init(name: "Spoto Press", muscle: .chest, equipment: .barbell),
        .init(name: "Pin Press", muscle: .chest, equipment: .barbell),
        .init(name: "Board Press", muscle: .chest, equipment: .barbell),
        .init(name: "Dumbbell Bench Press", muscle: .chest, equipment: .dumbbell),
        .init(name: "Incline Dumbbell Press", muscle: .chest, equipment: .dumbbell),
        .init(name: "Decline Dumbbell Press", muscle: .chest, equipment: .dumbbell),
        .init(name: "Dumbbell Floor Press", muscle: .chest, equipment: .dumbbell),
        .init(name: "Dumbbell Fly", muscle: .chest, equipment: .dumbbell),
        .init(name: "Incline Dumbbell Fly", muscle: .chest, equipment: .dumbbell),
        .init(name: "Dumbbell Pullover", muscle: .chest, equipment: .dumbbell),
        .init(name: "Squeeze Press", muscle: .chest, equipment: .dumbbell),
        .init(name: "Cable Fly", muscle: .chest, equipment: .cable),
        .init(name: "Low-to-High Cable Fly", muscle: .chest, equipment: .cable),
        .init(name: "High-to-Low Cable Fly", muscle: .chest, equipment: .cable),
        .init(name: "Cable Crossover", muscle: .chest, equipment: .cable),
        .init(name: "Machine Chest Press", muscle: .chest, equipment: .machine),
        .init(name: "Incline Machine Press", muscle: .chest, equipment: .machine),
        .init(name: "Pec Deck", muscle: .chest, equipment: .machine),
        .init(name: "Smith Machine Bench Press", muscle: .chest, equipment: .smith),
        .init(name: "Smith Machine Incline Press", muscle: .chest, equipment: .smith),
        .init(name: "Push-Up", muscle: .chest, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Incline Push-Up", muscle: .chest, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Decline Push-Up", muscle: .chest, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Diamond Push-Up", muscle: .chest, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Wide Push-Up", muscle: .chest, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Archer Push-Up", muscle: .chest, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Deficit Push-Up", muscle: .chest, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Chest Dip", muscle: .chest, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Ring Push-Up", muscle: .chest, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Banded Chest Press", muscle: .chest, equipment: .band),
        // MARK: back
        .init(name: "Deadlift", muscle: .back, equipment: .barbell),
        .init(name: "Sumo Deadlift", muscle: .back, equipment: .barbell),
        .init(name: "Deficit Deadlift", muscle: .back, equipment: .barbell),
        .init(name: "Rack Pull", muscle: .back, equipment: .barbell),
        .init(name: "Snatch-Grip Deadlift", muscle: .back, equipment: .barbell),
        .init(name: "Trap Bar Deadlift", muscle: .back, equipment: .barbell),
        .init(name: "Barbell Row", muscle: .back, equipment: .barbell),
        .init(name: "Pendlay Row", muscle: .back, equipment: .barbell),
        .init(name: "Yates Row", muscle: .back, equipment: .barbell),
        .init(name: "Meadows Row", muscle: .back, equipment: .barbell),
        .init(name: "T-Bar Row", muscle: .back, equipment: .barbell),
        .init(name: "Barbell Shrug", muscle: .back, equipment: .barbell),
        .init(name: "Good Morning", muscle: .back, equipment: .barbell),
        .init(name: "Dumbbell Row", muscle: .back, equipment: .dumbbell),
        .init(name: "Chest-Supported Dumbbell Row", muscle: .back, equipment: .dumbbell),
        .init(name: "Dumbbell Shrug", muscle: .back, equipment: .dumbbell),
        .init(name: "Dumbbell Pullover (Back)", muscle: .back, equipment: .dumbbell),
        .init(name: "Lat Pulldown", muscle: .back, equipment: .cable),
        .init(name: "Wide-Grip Pulldown", muscle: .back, equipment: .cable),
        .init(name: "Close-Grip Pulldown", muscle: .back, equipment: .cable),
        .init(name: "Reverse-Grip Pulldown", muscle: .back, equipment: .cable),
        .init(name: "Single-Arm Pulldown", muscle: .back, equipment: .cable),
        .init(name: "Straight-Arm Pulldown", muscle: .back, equipment: .cable),
        .init(name: "Seated Cable Row", muscle: .back, equipment: .cable),
        .init(name: "Single-Arm Cable Row", muscle: .back, equipment: .cable),
        .init(name: "Face Pull (Rope)", muscle: .back, equipment: .cable),
        .init(name: "Cable Shrug", muscle: .back, equipment: .cable),
        .init(name: "Machine Row", muscle: .back, equipment: .machine),
        .init(name: "Chest-Supported Machine Row", muscle: .back, equipment: .machine),
        .init(name: "Hammer Strength Row", muscle: .back, equipment: .machine),
        .init(name: "Assisted Pull-Up", muscle: .back, equipment: .machine),
        .init(name: "Back Extension", muscle: .back, equipment: .machine, tracking: .repsOnly),
        .init(name: "Pull-Up", muscle: .back, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Chin-Up", muscle: .back, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Neutral-Grip Pull-Up", muscle: .back, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Wide-Grip Pull-Up", muscle: .back, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Weighted Pull-Up", muscle: .back, equipment: .bodyweight),
        .init(name: "Inverted Row", muscle: .back, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Ring Row", muscle: .back, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Dead Hang", muscle: .back, equipment: .bodyweight, tracking: .duration),
        .init(name: "Kettlebell Row", muscle: .back, equipment: .kettlebell),
        .init(name: "Band Pull-Apart", muscle: .back, equipment: .band, tracking: .repsOnly),
        .init(name: "Sled Row", muscle: .back, equipment: .sled),
        // MARK: shoulders
        .init(name: "Overhead Press", muscle: .shoulders, equipment: .barbell),
        .init(name: "Push Press", muscle: .shoulders, equipment: .barbell),
        .init(name: "Push Jerk", muscle: .shoulders, equipment: .barbell),
        .init(name: "Behind-the-Neck Press", muscle: .shoulders, equipment: .barbell),
        .init(name: "Z Press", muscle: .shoulders, equipment: .barbell),
        .init(name: "Upright Row", muscle: .shoulders, equipment: .barbell),
        .init(name: "Seated Dumbbell Press", muscle: .shoulders, equipment: .dumbbell),
        .init(name: "Standing Dumbbell Press", muscle: .shoulders, equipment: .dumbbell),
        .init(name: "Arnold Press", muscle: .shoulders, equipment: .dumbbell),
        .init(name: "Lateral Raise", muscle: .shoulders, equipment: .dumbbell),
        .init(name: "Front Raise", muscle: .shoulders, equipment: .dumbbell),
        .init(name: "Rear Delt Fly", muscle: .shoulders, equipment: .dumbbell),
        .init(name: "Dumbbell Shoulder Shrug Press", muscle: .shoulders, equipment: .dumbbell),
        .init(name: "Cable Lateral Raise", muscle: .shoulders, equipment: .cable),
        .init(name: "Cable Front Raise", muscle: .shoulders, equipment: .cable),
        .init(name: "Cable Rear Delt Fly", muscle: .shoulders, equipment: .cable),
        .init(name: "Face Pull", muscle: .shoulders, equipment: .cable),
        .init(name: "Cable Upright Row", muscle: .shoulders, equipment: .cable),
        .init(name: "Machine Shoulder Press", muscle: .shoulders, equipment: .machine),
        .init(name: "Machine Lateral Raise", muscle: .shoulders, equipment: .machine),
        .init(name: "Reverse Pec Deck", muscle: .shoulders, equipment: .machine),
        .init(name: "Smith Machine Shoulder Press", muscle: .shoulders, equipment: .smith),
        .init(name: "Pike Push-Up", muscle: .shoulders, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Handstand Push-Up", muscle: .shoulders, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Handstand Hold", muscle: .shoulders, equipment: .bodyweight, tracking: .duration),
        .init(name: "Kettlebell Press", muscle: .shoulders, equipment: .kettlebell),
        .init(name: "Kettlebell Halo", muscle: .shoulders, equipment: .kettlebell, tracking: .repsOnly),
        .init(name: "Band Lateral Raise", muscle: .shoulders, equipment: .band, tracking: .repsOnly),
        // MARK: arms
        .init(name: "Barbell Curl", muscle: .arms, equipment: .barbell),
        .init(name: "EZ-Bar Curl", muscle: .arms, equipment: .barbell),
        .init(name: "Preacher Curl", muscle: .arms, equipment: .barbell),
        .init(name: "Reverse Curl", muscle: .arms, equipment: .barbell),
        .init(name: "Drag Curl", muscle: .arms, equipment: .barbell),
        .init(name: "Skull Crusher", muscle: .arms, equipment: .barbell),
        .init(name: "JM Press", muscle: .arms, equipment: .barbell),
        .init(name: "Barbell Wrist Curl", muscle: .arms, equipment: .barbell),
        .init(name: "Dumbbell Curl", muscle: .arms, equipment: .dumbbell),
        .init(name: "Incline Dumbbell Curl", muscle: .arms, equipment: .dumbbell),
        .init(name: "Hammer Curl", muscle: .arms, equipment: .dumbbell),
        .init(name: "Concentration Curl", muscle: .arms, equipment: .dumbbell),
        .init(name: "Zottman Curl", muscle: .arms, equipment: .dumbbell),
        .init(name: "Overhead Dumbbell Extension", muscle: .arms, equipment: .dumbbell),
        .init(name: "Dumbbell Kickback", muscle: .arms, equipment: .dumbbell),
        .init(name: "Tate Press", muscle: .arms, equipment: .dumbbell),
        .init(name: "Dumbbell Wrist Curl", muscle: .arms, equipment: .dumbbell),
        .init(name: "Cable Curl", muscle: .arms, equipment: .cable),
        .init(name: "Rope Hammer Curl", muscle: .arms, equipment: .cable),
        .init(name: "Bayesian Curl", muscle: .arms, equipment: .cable),
        .init(name: "Triceps Pushdown", muscle: .arms, equipment: .cable),
        .init(name: "Rope Pushdown", muscle: .arms, equipment: .cable),
        .init(name: "Overhead Cable Extension", muscle: .arms, equipment: .cable),
        .init(name: "Single-Arm Pushdown", muscle: .arms, equipment: .cable),
        .init(name: "Machine Curl", muscle: .arms, equipment: .machine),
        .init(name: "Machine Triceps Extension", muscle: .arms, equipment: .machine),
        .init(name: "Assisted Dip", muscle: .arms, equipment: .machine),
        .init(name: "Dip", muscle: .arms, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Weighted Dip", muscle: .arms, equipment: .bodyweight),
        .init(name: "Bench Dip", muscle: .arms, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Close-Grip Push-Up", muscle: .arms, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Band Curl", muscle: .arms, equipment: .band, tracking: .repsOnly),
        .init(name: "Band Pushdown", muscle: .arms, equipment: .band, tracking: .repsOnly),
        .init(name: "Farmer's Carry", muscle: .arms, equipment: .dumbbell, tracking: .duration),
        // MARK: legs
        .init(name: "Back Squat", muscle: .legs, equipment: .barbell),
        .init(name: "Front Squat", muscle: .legs, equipment: .barbell),
        .init(name: "High-Bar Squat", muscle: .legs, equipment: .barbell),
        .init(name: "Low-Bar Squat", muscle: .legs, equipment: .barbell),
        .init(name: "Box Squat", muscle: .legs, equipment: .barbell),
        .init(name: "Pause Squat", muscle: .legs, equipment: .barbell),
        .init(name: "Overhead Squat", muscle: .legs, equipment: .barbell),
        .init(name: "Zercher Squat", muscle: .legs, equipment: .barbell),
        .init(name: "Split Squat", muscle: .legs, equipment: .barbell),
        .init(name: "Bulgarian Split Squat", muscle: .legs, equipment: .barbell),
        .init(name: "Romanian Deadlift", muscle: .legs, equipment: .barbell),
        .init(name: "Stiff-Leg Deadlift", muscle: .legs, equipment: .barbell),
        .init(name: "Barbell Lunge", muscle: .legs, equipment: .barbell),
        .init(name: "Barbell Step-Up", muscle: .legs, equipment: .barbell),
        .init(name: "Barbell Calf Raise", muscle: .legs, equipment: .barbell),
        .init(name: "Goblet Squat", muscle: .legs, equipment: .dumbbell),
        .init(name: "Dumbbell Lunge", muscle: .legs, equipment: .dumbbell),
        .init(name: "Walking Lunge", muscle: .legs, equipment: .dumbbell),
        .init(name: "Reverse Lunge", muscle: .legs, equipment: .dumbbell),
        .init(name: "Lateral Lunge", muscle: .legs, equipment: .dumbbell),
        .init(name: "Dumbbell Step-Up", muscle: .legs, equipment: .dumbbell),
        .init(name: "Dumbbell Bulgarian Split Squat", muscle: .legs, equipment: .dumbbell),
        .init(name: "Dumbbell RDL", muscle: .legs, equipment: .dumbbell),
        .init(name: "Leg Press", muscle: .legs, equipment: .machine),
        .init(name: "Hack Squat", muscle: .legs, equipment: .machine),
        .init(name: "V-Squat", muscle: .legs, equipment: .machine),
        .init(name: "Leg Extension", muscle: .legs, equipment: .machine),
        .init(name: "Seated Leg Curl", muscle: .legs, equipment: .machine),
        .init(name: "Lying Leg Curl", muscle: .legs, equipment: .machine),
        .init(name: "Standing Leg Curl", muscle: .legs, equipment: .machine),
        .init(name: "Standing Calf Raise", muscle: .legs, equipment: .machine),
        .init(name: "Seated Calf Raise", muscle: .legs, equipment: .machine),
        .init(name: "Calf Press", muscle: .legs, equipment: .machine),
        .init(name: "Adductor Machine", muscle: .legs, equipment: .machine),
        .init(name: "Abductor Machine", muscle: .legs, equipment: .machine),
        .init(name: "Smith Machine Squat", muscle: .legs, equipment: .smith),
        .init(name: "Smith Machine Lunge", muscle: .legs, equipment: .smith),
        .init(name: "Smith Machine Calf Raise", muscle: .legs, equipment: .smith),
        .init(name: "Cable Pull-Through", muscle: .legs, equipment: .cable),
        .init(name: "Cable Kickback", muscle: .legs, equipment: .cable),
        .init(name: "Bodyweight Squat", muscle: .legs, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Pistol Squat", muscle: .legs, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Jump Squat", muscle: .legs, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Wall Sit", muscle: .legs, equipment: .bodyweight, tracking: .duration),
        .init(name: "Nordic Curl", muscle: .legs, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Sissy Squat", muscle: .legs, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Calf Raise", muscle: .legs, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Box Jump", muscle: .legs, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Kettlebell Goblet Squat", muscle: .legs, equipment: .kettlebell),
        .init(name: "Kettlebell Front Rack Squat", muscle: .legs, equipment: .kettlebell),
        .init(name: "Sled Push", muscle: .legs, equipment: .sled, tracking: .duration),
        .init(name: "Sled Drag", muscle: .legs, equipment: .sled, tracking: .duration),
        // MARK: glutes
        .init(name: "Hip Thrust", muscle: .glutes, equipment: .barbell),
        .init(name: "Glute Bridge", muscle: .glutes, equipment: .barbell),
        .init(name: "Single-Leg Hip Thrust", muscle: .glutes, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Machine Hip Thrust", muscle: .glutes, equipment: .machine),
        .init(name: "Cable Glute Kickback", muscle: .glutes, equipment: .cable),
        .init(name: "Band Hip Thrust", muscle: .glutes, equipment: .band, tracking: .repsOnly),
        .init(name: "Frog Pump", muscle: .glutes, equipment: .dumbbell),
        .init(name: "Banded Lateral Walk", muscle: .glutes, equipment: .band, tracking: .repsOnly),
        .init(name: "Clamshell", muscle: .glutes, equipment: .band, tracking: .repsOnly),
        .init(name: "Curtsy Lunge", muscle: .glutes, equipment: .dumbbell),
        .init(name: "Kettlebell Swing", muscle: .glutes, equipment: .kettlebell),
        .init(name: "Single-Leg RDL", muscle: .glutes, equipment: .dumbbell),
        .init(name: "45° Hyperextension", muscle: .glutes, equipment: .machine, tracking: .repsOnly),
        .init(name: "Reverse Hyperextension", muscle: .glutes, equipment: .machine),
        // MARK: core
        .init(name: "Plank", muscle: .core, equipment: .bodyweight, tracking: .duration),
        .init(name: "Side Plank", muscle: .core, equipment: .bodyweight, tracking: .duration),
        .init(name: "RKC Plank", muscle: .core, equipment: .bodyweight, tracking: .duration),
        .init(name: "Hollow Hold", muscle: .core, equipment: .bodyweight, tracking: .duration),
        .init(name: "L-Sit", muscle: .core, equipment: .bodyweight, tracking: .duration),
        .init(name: "Dead Bug", muscle: .core, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Bird Dog", muscle: .core, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Crunch", muscle: .core, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Bicycle Crunch", muscle: .core, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Sit-Up", muscle: .core, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "V-Up", muscle: .core, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Leg Raise", muscle: .core, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Hanging Leg Raise", muscle: .core, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Hanging Knee Raise", muscle: .core, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Toes to Bar", muscle: .core, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Mountain Climber", muscle: .core, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Flutter Kick", muscle: .core, equipment: .bodyweight, tracking: .duration),
        .init(name: "Russian Twist", muscle: .core, equipment: .ball, tracking: .repsOnly),
        .init(name: "Ab Wheel Rollout", muscle: .core, equipment: .other, tracking: .repsOnly),
        .init(name: "Dragon Flag", muscle: .core, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Cable Crunch", muscle: .core, equipment: .cable),
        .init(name: "Cable Woodchopper", muscle: .core, equipment: .cable),
        .init(name: "Pallof Press", muscle: .core, equipment: .cable),
        .init(name: "Machine Crunch", muscle: .core, equipment: .machine),
        .init(name: "Weighted Sit-Up", muscle: .core, equipment: .dumbbell),
        .init(name: "Suitcase Carry", muscle: .core, equipment: .dumbbell, tracking: .duration),
        .init(name: "Turkish Get-Up", muscle: .core, equipment: .kettlebell, tracking: .repsOnly),
        .init(name: "Medicine Ball Slam", muscle: .core, equipment: .ball, tracking: .repsOnly),
        .init(name: "Landmine Twist", muscle: .core, equipment: .barbell, tracking: .repsOnly),
        // MARK: fullBody
        .init(name: "Clean", muscle: .fullBody, equipment: .barbell),
        .init(name: "Power Clean", muscle: .fullBody, equipment: .barbell),
        .init(name: "Hang Clean", muscle: .fullBody, equipment: .barbell),
        .init(name: "Clean & Jerk", muscle: .fullBody, equipment: .barbell),
        .init(name: "Snatch", muscle: .fullBody, equipment: .barbell),
        .init(name: "Power Snatch", muscle: .fullBody, equipment: .barbell),
        .init(name: "Hang Snatch", muscle: .fullBody, equipment: .barbell),
        .init(name: "Clean Pull", muscle: .fullBody, equipment: .barbell),
        .init(name: "Snatch Pull", muscle: .fullBody, equipment: .barbell),
        .init(name: "Thruster", muscle: .fullBody, equipment: .barbell),
        .init(name: "Barbell Complex", muscle: .fullBody, equipment: .barbell),
        .init(name: "Landmine Press", muscle: .fullBody, equipment: .barbell),
        .init(name: "Dumbbell Thruster", muscle: .fullBody, equipment: .dumbbell),
        .init(name: "Dumbbell Snatch", muscle: .fullBody, equipment: .dumbbell),
        .init(name: "Devil's Press", muscle: .fullBody, equipment: .dumbbell),
        .init(name: "Man Maker", muscle: .fullBody, equipment: .dumbbell, tracking: .repsOnly),
        .init(name: "Kettlebell Clean", muscle: .fullBody, equipment: .kettlebell),
        .init(name: "Kettlebell Snatch", muscle: .fullBody, equipment: .kettlebell),
        .init(name: "Kettlebell Thruster", muscle: .fullBody, equipment: .kettlebell),
        .init(name: "Burpee", muscle: .fullBody, equipment: .bodyweight, tracking: .repsOnly),
        .init(name: "Bear Crawl", muscle: .fullBody, equipment: .bodyweight, tracking: .duration),
        .init(name: "Battle Ropes", muscle: .fullBody, equipment: .other, tracking: .duration),
        .init(name: "Wall Ball", muscle: .fullBody, equipment: .ball, tracking: .repsOnly),
        // MARK: cardio
        .init(name: "Rowing Machine", muscle: .cardio, equipment: .machine, tracking: .duration),
        .init(name: "Treadmill Run", muscle: .cardio, equipment: .machine, tracking: .duration),
        .init(name: "Incline Walk", muscle: .cardio, equipment: .machine, tracking: .duration),
        .init(name: "Stationary Bike", muscle: .cardio, equipment: .machine, tracking: .duration),
        .init(name: "Assault Bike", muscle: .cardio, equipment: .machine, tracking: .duration),
        .init(name: "Stair Climber", muscle: .cardio, equipment: .machine, tracking: .duration),
        .init(name: "Elliptical", muscle: .cardio, equipment: .machine, tracking: .duration),
        .init(name: "Ski Erg", muscle: .cardio, equipment: .machine, tracking: .duration),
        .init(name: "Jump Rope", muscle: .cardio, equipment: .other, tracking: .duration),
        .init(name: "Outdoor Run", muscle: .cardio, equipment: .bodyweight, tracking: .duration),
        .init(name: "Swim", muscle: .cardio, equipment: .bodyweight, tracking: .duration),
        .init(name: "Sprint Intervals", muscle: .cardio, equipment: .bodyweight, tracking: .duration)
    ]

    /// Idempotent, and safe to call on every launch: existing rows are left
    /// alone (including ones the user hid or renamed) and only genuinely new
    /// library entries are inserted, so updates that expand the library reach
    /// people who already have a store.
    @MainActor
    static func bootstrap(_ context: ModelContext) {
        let existing = (try? context.fetch(FetchDescriptor<Exercise>())) ?? []
        var known = Set(existing.map { $0.name.lowercased() })

        for row in exercises where !known.contains(row.name.lowercased()) {
            known.insert(row.name.lowercased())
            context.insert(
                Exercise(
                    name: row.name,
                    muscle: row.muscle,
                    equipment: row.equipment,
                    tracking: row.tracking
                )
            )
        }

        let athleteCount = (try? context.fetchCount(FetchDescriptor<Athlete>())) ?? 0
        if athleteCount == 0 {
            context.insert(Athlete(name: "You"))
        }

        context.saveChanges()
    }
}
